# Generated by Django 5.1.7 on 2025-04-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('availability', models.BooleanField(default=True)),
                ('specialization', models.CharField(max_length=255)),
                ('info', models.TextField()),
                ('appointment_fee', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
